### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'pulses.data.map')

### ISSUE THREAD

**Issue by shinchan-02** [paoliniluis/pulse-migrator#2]
Authenticating
Authenticated, now getting collections
Got collections, now getting pulses
145 |
146 |     if (pulses.total > 0) {
147 |         pulses.data.map(pulse => pulse.collection = collection_id)
148 |     }
149 |
150 |     pulses.data.map(pulse => {
                 ^
TypeError: undefined is not an object (evaluating 'pulses.data.map')
      at /data/pulse-migrator/index.ts:150:12

**Comment by dragonsahead** [comment]
version of metabase? seems that there are no pulses in that collection or something is weird on the response

**Comment by shinchan-02** [comment]
using v0.38.0.1 and having more than 800 pulses

**Comment by dragonsahead** [comment]
This is for versions > 40, you can’t migrate pulses on such an older
version simply because subscriptions didn’t exist back then

**Comment by shinchan-02** [comment]
oh cool , thanks for  reply 

will move first to >0.40 , then will try to move pulse 

btw please mention this in your readme .. it will be helpful

**Comment by dragonsahead** [comment]
done

**Comment by shinchan-02** [comment]
pulse migrated to  dashboard subscription  👍🏻
but if there is no dashboard .. dashboard subscription will not work 😮‍💨
